//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PbxManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneCalls
    {
        public int Id { get; set; }
        public int CallerId { get; set; }
        public string ReceiverPhoneNumber { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
    
        public virtual Subscribers Subscribers { get; set; }
    }
}
